# Generated by Django 6.0.2 on 2026-02-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('board_size', models.PositiveSmallIntegerField(choices=[(9, '9x9'), (13, '13x13'), (19, '19x19')], default=19)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='black', to='game.players')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='white', to='game.players')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.games')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='game.positions')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_games', to='game.positions'),
        ),
    ]
