# Generated by Django 6.0.2 on 2026-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='black_player',
        ),
        migrations.RemoveField(
            model_name='games',
            name='white_player',
        ),
        migrations.AddField(
            model_name='games',
            name='current_player',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='black', max_length=5),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(default='Новая игра', max_length=128),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
