# Generated by Django 6.0.2 on 2026-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_games_black_player_remove_games_white_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='board',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
